name: Main

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: GitHub
      url: ${{ steps.backup-data.outputs.artifact-url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test

      - name: Download data
        run: make download

      - name: Backup data
        id: backup-data
        uses: actions/upload-artifact@v4
        with:
          name: bgg-data-backup
          path: data/
          if-no-files-found: error
          retention-days: 90
